### ISSUE TITLE
Update repo to use multimodality shaders

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/tomo_raycaster2_examples#2]
Hi @AIRTucha ,

can you just put in the phantom data and create 1 or 2 examples here?

Thanks.

**Comment by AIRTucha** [comment]
Hi, Nicolas, I did not get. USCT has only two samples of data: the breast 2 (port 10003) and the phantom (port 10002), I don't have any other data to create examples.

**Comment by nicolaisi** [comment]
Hi @AIRTucha ,

can you help check this
https://github.com/kit-ipe/tomo_raycaster2_examples/tree/master/examples/multimodality

![screenshot from 2015-11-23 12 10 59](https://cloud.githubusercontent.com/assets/2225781/11335348/e4c7301a-91db-11e5-9e09-010d5428dfcd.png)

Maybe my config setup is wrong. Can you help me look into it?

**Comment by AIRTucha** [comment]
Oh, ok, I see. So, you are right, you config is a little bit wrong. Please, try l = 5, s = 1, color_factor = 0.4

**Comment by nicolaisi** [comment]
Hmm, your setting gave a better view, but why what I get here is different from what we see on port 10002?

I use fusion with your setting, I get this:

![screenshot from 2015-11-23 15 41 07](https://cloud.githubusercontent.com/assets/2225781/11339309/4235a1a6-91f9-11e5-9b69-00106138e7cf.png)

The image I see from port 10002 is:

![screenshot from 2015-11-23 15 42 08](https://cloud.githubusercontent.com/assets/2225781/11339333/62732754-91f9-11e5-9218-84a9eadbb6ea.png)

If you have time, can you include in examples on different view? I already included the phantom data in this repository.

**Comment by AIRTucha** [comment]
Hi, Nicolas, I am very sorry, I am extremely short in time right now, next week I have couple of seminars. I will try to take a look at this problem until the week end. You can write me here airtucha@icloud.com or call Skype airtucha.

**Comment by AIRTucha** [comment]
![settings](https://cloud.githubusercontent.com/assets/10846716/11369834/91ffe81a-92c9-11e5-9656-4067c8537322.png)
Please, try the settings it works for me.

**Comment by nicolaisi** [comment]
You can do it when you are free, after all your seminars. Thanks for the setting, I'll try it, if its ok, I'll update it in this repo.

**Comment by AIRTucha** [comment]
what do you mean under "different view"?

**Comment by nicolaisi** [comment]
I am referring to different shaders, such as fusion, attenuation, sound speed and so on.

Each of these has an optimal setting and I think you are probably one of the few who knows which settings is best for each shader .

It would be great if we can have it here as well, I know now we have it in usct-vis. But here serves as a very very basic implementation.

**Comment by AIRTucha** [comment]
Actually, all of them have same settings, except CuttOff modes, CuttOff should have higher hMax(for example 0.85). 

Several shaders also look like very nice if you will set them like that : 
* opacity = 20
* darkness = 0
* l= 10
* s= 2
* minRefl = 20
* maxRefl = 100

But I don't have any other cool settings.

**Comment by nicolaisi** [comment]
It's good, I tried your setting and got the same result.

5c0065ff99e57c9364223af46d630b663f52f384
